version: '3'

services:
    app:
     image: jenkins:latest
     ports:
     - "8089:8080"
     volumes:
        type: bind
        source: jenkins
        target: /var/jenkins_home
     deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == docker-slave.node.com  #node hostname is mandatory
