version: '3'

services:
    app:
     image: jenkins:latest
     ports:
     - "8089:8080"
     volumes:
        - jenkins1:/var/jenkins_home
     deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
